# Generated by Django 2.2.10 on 2020-02-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ocorrencia', models.CharField(max_length=150)),
                ('fator_nome', models.CharField(max_length=150)),
                ('fator_aspecto', models.CharField(max_length=150)),
                ('fator_condicionante', models.CharField(max_length=150)),
                ('fator_area', models.CharField(max_length=150)),
                ('fator_detalhe_fator', models.CharField(max_length=150)),
                ('fator_dia_extracao', models.CharField(max_length=150)),
            ],
        ),
    ]
