# Generated by Django 2.2.10 on 2020-02-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacaoSeg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacaoseg',
            name='recomendacao_conteudo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recomendacaoseg',
            name='recomendacao_feedback',
            field=models.CharField(max_length=500),
        ),
    ]
